#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.
#
################################################################################

version: "3.7"

services:
  #debug:
  #  volumes:
  #    - logging-ranger-${ZONE_NAME}:/debug/ranger-${ZONE_NAME}

  # Fusion Ranger Proxy
  fusion-ranger-proxy-${ZONE_NAME}:
    image: wandisco/fusion-ranger-proxy-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    depends_on:
      - fusion-server-${ZONE_NAME}
    networks:
      - fusion
    env_file:
      - "${ZONE_ENV}"
    ports:
      - "${FUSION_RANGER_PROXY_PORT}:${FUSION_RANGER_PROXY_PORT}"
    volumes:
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-etc-hadoop:/etc/hadoop

networks:
  # One Docker network is shared between both zones
  fusion:

volumes:
  fusion-${ZONE_NAME}-etc-wandisco:
  fusion-${ZONE_NAME}-etc-hadoop:

